# Load datasets

In [ ]:
import pandas as pd

# Load dataset
BF1 = pd.read_csv('ET_Monthly_BF1_ensemble.csv')
# Convert Month_Year column to datetime format
BF1['date'] = pd.to_datetime(BF1['date'], format='%Y/%m/%d')

# Load dataset
BF2 = pd.read_csv('ET_Monthly_BF2_ensemble.csv')
# Convert Month_Year column to datetime format
BF2['date'] = pd.to_datetime(BF2['date'], format='%Y/%m/%d')

# Load dataset
CP3 = pd.read_csv('ET_Monthly_CP3_ensemble.csv')
# Convert Month_Year column to datetime format
CP3['date'] = pd.to_datetime(CP3['date'], format='%Y/%m/%d')

# Load dataset
CP6 = pd.read_csv('ET_Monthly_CP6_ensemble.csv')
# Convert Month_Year column to datetime format
CP6['date'] = pd.to_datetime(CP6['date'], format='%Y/%m/%d')

# Load dataset
CP9 = pd.read_csv('ET_Monthly_CP9_ensemble.csv')
# Convert Month_Year column to datetime format
CP9['date'] = pd.to_datetime(CP9['date'], format='%Y/%m/%d')

# Load dataset
EW1 = pd.read_csv('ET_Monthly_EW1_ensemble.csv')
# Convert Month_Year column to datetime format
EW1['date'] = pd.to_datetime(EW1['date'], format='%Y/%m/%d')

# Load dataset
EW2 = pd.read_csv('ET_Monthly_EW2_ensemble.csv')
# Convert Month_Year column to datetime format
EW2['date'] = pd.to_datetime(EW2['date'], format='%Y/%m/%d')

# Load dataset
EZU = pd.read_csv('ET_Monthly_EZU_ensemble.csv')
# Convert Month_Year column to datetime format
EZU['date'] = pd.to_datetime(EZU['date'], format='%Y/%m/%d')

# Load dataset
JHK = pd.read_csv('ET_Monthly_JHK_ensemble.csv')
# Convert Month_Year column to datetime format
JHK['date'] = pd.to_datetime(JHK['date'], format='%Y/%m/%d')

# Load dataset
MB1 = pd.read_csv('ET_Monthly_MB1_ensemble.csv')
# Convert Month_Year column to datetime format
MB1['date'] = pd.to_datetime(MB1['date'], format='%Y/%m/%d')

# Load dataset
MB2 = pd.read_csv('ET_Monthly_MB2_ensemble.csv')
# Convert Month_Year column to datetime format
MB2['date'] = pd.to_datetime(MB2['date'], format='%Y/%m/%d')

# Load dataset
MCP = pd.read_csv('ET_Monthly_MCP_ensemble.csv')
# Convert Month_Year column to datetime format
MCP['date'] = pd.to_datetime(MCP['date'], format='%Y/%m/%d')

# Load dataset
MLP = pd.read_csv('ET_Monthly_MLP_ensemble.csv')
# Convert Month_Year column to datetime format
MLP['date'] = pd.to_datetime(MLP['date'], format='%Y/%m/%d')

# Load dataset
SKU = pd.read_csv('ET_Monthly_SKU_ensemble.csv')
# Convert Month_Year column to datetime format
SKU['date'] = pd.to_datetime(SKU['date'], format='%Y/%m/%d')

# Average data according to month (x12 samples per site)

In [ ]:
# Extract month for grouping, drop the date column, and calculate monthly mean for each dataframe
BF1['month'] = BF1['date'].dt.month
BF1 = BF1.drop(columns=['date'])
monthly_means_BF1 = BF1.groupby('month').mean()
monthly_means_BF1.to_csv('monthly_means_BF1.csv')

BF2['month'] = BF2['date'].dt.month
BF2 = BF2.drop(columns=['date'])
monthly_means_BF2 = BF2.groupby('month').mean()
monthly_means_BF2.to_csv('monthly_means_BF2.csv')

CP3['month'] = CP3['date'].dt.month
CP3 = CP3.drop(columns=['date'])
monthly_means_CP3 = CP3.groupby('month').mean()
monthly_means_CP3.to_csv('monthly_means_CP3.csv')

CP6['month'] = CP6['date'].dt.month
CP6 = CP6.drop(columns=['date'])
monthly_means_CP6 = CP6.groupby('month').mean()
monthly_means_CP6.to_csv('monthly_means_CP6.csv')

CP9['month'] = CP9['date'].dt.month
CP9 = CP9.drop(columns=['date'])
monthly_means_CP9 = CP9.groupby('month').mean()
monthly_means_CP9.to_csv('monthly_means_CP9.csv')

EW1['month'] = EW1['date'].dt.month
EW1 = EW1.drop(columns=['date'])
monthly_means_EW1 = EW1.groupby('month').mean()
monthly_means_EW1.to_csv('monthly_means_EW1.csv')

EW2['month'] = EW2['date'].dt.month
EW2 = EW2.drop(columns=['date'])
monthly_means_EW2 = EW2.groupby('month').mean()
monthly_means_EW2.to_csv('monthly_means_EW2.csv')

EZU['month'] = EZU['date'].dt.month
EZU = EZU.drop(columns=['date'])
monthly_means_EZU = EZU.groupby('month').mean()
monthly_means_EZU.to_csv('monthly_means_EZU.csv')

JHK['month'] = JHK['date'].dt.month
JHK = JHK.drop(columns=['date'])
monthly_means_JHK = JHK.groupby('month').mean()
monthly_means_JHK.to_csv('monthly_means_JHK.csv')

MB1['month'] = MB1['date'].dt.month
MB1 = MB1.drop(columns=['date'])
monthly_means_MB1 = MB1.groupby('month').mean()
monthly_means_MB1.to_csv('monthly_means_MB1.csv')

MB2['month'] = MB2['date'].dt.month
MB2 = MB2.drop(columns=['date'])
monthly_means_MB2 = MB2.groupby('month').mean()
monthly_means_MB2.to_csv('monthly_means_MB2.csv')

MCP['month'] = MCP['date'].dt.month
MCP = MCP.drop(columns=['date'])
monthly_means_MCP = MCP.groupby('month').mean()
monthly_means_MCP.to_csv('monthly_means_MCP.csv')

MLP['month'] = MLP['date'].dt.month
MLP = MLP.drop(columns=['date'])
monthly_means_MLP = MLP.groupby('month').mean()
monthly_means_MLP.to_csv('monthly_means_MLP.csv')

SKU['month'] = SKU['date'].dt.month
SKU = SKU.drop(columns=['date'])
monthly_means_SKU = SKU.groupby('month').mean()
monthly_means_SKU.to_csv('monthly_means_SKU.csv')

In [ ]:
# Sanity check (optional)
monthly_means_MCP

          min_ET  max_ET  median_ET    mean_ET    field_et
month
1      54.650087  114.00  78.772524  81.014626  113.922302
2      61.095627   96.20  68.592478  73.426157  104.134699
3      51.459095   94.40  75.386842  73.305844  102.010711
4      40.824661   77.55  48.280640  53.652411   66.254550
5      25.901954   56.40  41.316798  40.866778   51.949294
6            NaN     NaN        NaN        NaN         NaN
7            NaN     NaN        NaN        NaN         NaN
8            NaN     NaN        NaN        NaN         NaN
9            NaN     NaN        NaN        NaN         NaN
10           NaN     NaN        NaN        NaN         NaN
11     42.919137   88.60  69.621209  69.480074   93.280983
12     63.798185  102.70  77.314583  79.853308  101.084664